### ISSUE TITLE
MEmuConsole: This application failed to start because no Qt platform plugin ....

### ISSUE THREAD

**Issue by longnguyenQB** [pyclashbot/pymemuc#110]
When i package using pyinstaller==6.1.0, run application i get this error. Can you help me?

**Comment by martinmiglio** [comment]
PyMemuc only uses standard Python libraries so it should compile fine using pyinstaller, maybe check your other dependencies.

Try creating a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) with only PyMemuc and pyinstaller to see if this is actually a problem caused by this library.

**Comment by longnguyenQB** [comment]
i used pyinstaller==6.1.0, pyqt5, pyqt6.  But it not work!

**Comment by martinmiglio** [comment]
Well it looks like an issue with PyQT based on the error message. Try without those to see if this error still appears.

My minimal reproduction would look something like this:

```python
# main.py or entry point for pyinstaller
from pymemuc import PyMemuc

print(PyMemuc.__dict__)
```
